todolist/main/urls.py
from django.urls import path

from . import views
from .views import AddTaskView

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add_task/', AddTaskView.as_view(), name='add_task'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('view-other-users-tasks/', views.view_other_users_tasks, name='view_other_users_tasks'),
    path('add-task-for-user/', views.add_task_for_user, name='add_task_for_user'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

]

todolist/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Task(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    header = models.CharField(max_length=40)
    dispatcher = models.TextField(blank=True)
    isDo=models.BooleanField(default=False)

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

    def __str__(self):
        return self.header

todolist/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import CustomUser, Task


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username',)


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['header', 'dispatcher']


class TaskFormEdit(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['header', 'dispatcher', 'isDo']


class AddTaskToUserForm(forms.Form):
    user = forms.ModelChoiceField(label='User', queryset=CustomUser.objects.all())
    header = forms.CharField(label='Header', max_length=40)
    dispatcher = forms.CharField(label='Dispatcher', widget=forms.Textarea, required=False)


    def save(self):
        user = self.cleaned_data['user']
        header = self.cleaned_data['header']
        dispatcher = self.cleaned_data['dispatcher']
        task = Task.objects.create(user=user, header=header, dispatcher=dispatcher)
        return task

todolist/main/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from .forms import CustomUserCreationForm, CustomAuthenticationForm
from .forms import TaskForm, TaskFormEdit, AddTaskToUserForm
from .models import Task


def view_other_users_tasks(request):
    tasks = Task.objects.exclude(user__is_superuser=True)
    return render(request, 'main/other_users_tasks.html', {'tasks': tasks})


def add_task_for_user(request):
    if request.method == 'POST':
        form = AddTaskToUserForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect('view_other_users_tasks')
    else:
        form = AddTaskToUserForm()
    return render(request, 'main/add_task_for_user.html', {'form': form})


def edit_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        form = TaskFormEdit(request.POST, instance=task)
        if form.is_valid():
            form.save()

            if request.user.is_superuser and task.user != request.user:
                redirect_url = 'view_other_users_tasks'
            else:
                redirect_url = 'home'
            return redirect(redirect_url)
    else:
        form = TaskFormEdit(instance=task)

    return render(request, 'main/edit_task.html', {'form': form})


class AddTaskView(View):
    def get(self, request):
        form = TaskForm()
        return render(request, 'main/add_task.html', {'form': form})

    def post(self, request):
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('home')
        return render(request, 'main/add_task.html', {'form': form})


def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        task.delete()
        if request.user.is_superuser and task.user != request.user:
            redirect_url = 'view_other_users_tasks'
        else:
            redirect_url = 'home'
        return redirect(redirect_url)
    return redirect('home')


from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'Вы успешно зарегистрировались!')
            return redirect('home')
        else:
            # Check for specific errors and display corresponding error messages
            if 'username' in form.errors:
                error_message = form.errors['username'][0]
                messages.error(request, f'Ошибка: {error_message}')
            if 'password1' in form.errors:
                error_message = form.errors['password1'][0]
                messages.error(request, f'Ошибка: {error_message}')
            if 'password2' in form.errors:
                error_message = form.errors['password2'][0]
                messages.error(request, f'Ошибка: {error_message}')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Вы успешно вошли!')
            return redirect('home')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'Вы успешно вышли из системы!')
    return redirect('home')


def index(request):
    undone_tasks = Task.objects.filter(isDo=False).order_by('-pk')
    done_tasks = Task.objects.filter(isDo=True).order_by('-pk')
    tasks = list(undone_tasks) + list(done_tasks)
    return render(request, 'main/index.html', {'title': 'Главная страница сайта', 'tasks': tasks})

todolist/main/templates/main/add_task.html
{% extends 'main/base.html' %}

{% block title %}
{{ Добавить}}
{% endblock %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Добавить задачу</h2>
                            {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Ошибка!</strong> Пожалуйста, исправьте ошибки в форме.
                            </div>
                            {% endif %}
                            <form method="post">
                                {% csrf_token %}
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_header" class="form-label">Название</label>
                                    {{ form.header }}
                                </div>
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_dispatcher" class="form-label">Описание</label>
                                    {{ form.dispatcher }}
                                </div>
                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Создать
                                        задачу
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

todolist/main/templates/main/add_task_for_user.html
{% extends 'main/base.html' %}

{% block title %}
Добавить задачу
{% endblock %}


{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Добавить задачу</h2>
                            {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Ошибка!</strong> Пожалуйста, исправьте ошибки в форме.
                            </div>
                            {% endif %}
                            <form method="post">
                                {% csrf_token %}
                                <div data-mdb-input-init class="form-outline mb-4">
                                     <label for="id_user" class="form-label">Пользователь</label>
                                    {{ form.user }}
                                </div>
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_header" class="form-label">Название</label>
                                    {{ form.header }}
                                </div>
                                <div data-mdb-input-init class="form-outline mb-4">
                                     <label for="id_dispatcher" class="form-label">Описание</label>
                                    {{ form.dispatcher }}
                                </div>
                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Создать
                                        задачу
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

todolist/main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5/dist/css/bootstrap.min.css">

</head>
<body style="background:#f0f0f0;">
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h3 class="my-0 mr-md-auto font-weight-normal">To-Do List</h3>

     {% if user.is_authenticated %}
<nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="{% url 'home'%}">Мои задачи</a>
     {% if user.is_superuser %}
    <a class="p-2 text-dark" href="{% url 'view_other_users_tasks'%}">Задачи пользователей</a>
    {% endif %}
  </nav>
<a class="p-2 text-dark" style=" text-decoration: none;"><b> Добро пожаловать, {{ user.username }}!</b></a>
<a class="btn btn-outline-primary" href="{% url 'logout' %}">Выйти</a>
{% else %}
      <a class="p-2 text-dark mx-2" href="{% url 'home'%}">Главная</a>
{% if request.path == '/login/' %}

    <a class="btn btn-outline-primary mx-2" href="{% url 'register' %}">Зарегистрироваться</a>
{% elif request.path == '/register/' %}

    <a class="btn btn-outline-primary mx-2" href="{% url 'login' %}">Войти</a>
{% else %}
   <a class="btn btn-outline-primary mx-2" href="{% url 'login' %}">Войти</a>
        <a class="btn btn-outline-primary mx-2" href="{% url 'register' %}">Зарегистрироваться</a>
{% endif %}
{% endif %}

    </div>
  <div class="container" style=" margin-bottom: 35px;">{% block content %}{% endblock %}</div>

</body>
</html>

todolist/main/templates/main/edit_task.html
{% extends 'main/base.html' %}

{% block title %}
Редактирование задачи
{% endblock %}



{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Редактировать задачу</h2>
                            {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Ошибка!</strong> Пожалуйста, исправьте ошибки в форме.
                            </div>
                            {% endif %}
                            <form method="post">
                                {% csrf_token %}
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_header" class="form-label">Название</label>
                                    {{ form.header }}
                                </div>
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_dispatcher" class="form-label">Описание</label>
                                    {{ form.dispatcher }}
                                </div>
                                <div data-mdb-input-init class="form-outline mb-4">
                                    <label for="id_isDo" class="form-label">Выполнено</label>
                                    {{ form.isDo }}
                                </div>
                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                        Сохранить
                                        изменения
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

todolist/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<a href="{% url 'add_task' %}" class="btn btn-primary">Добавить задачу</a>
{%if user.is_superuser%}
<a href="{% url 'view_other_users_tasks' %}" class="btn btn-primary">Просмотреть задачи пользователей </a>
{% endif%}
{% if tasks %}
{% for task in tasks %}
{% if task.user == user %}
<div class="alert mt-2 {% if not task.isDo %}alert-danger{% else %}alert-success{% endif %}">
    <h3>{{ task.header }}</h3>
    <p>{{ task.dispatcher }}</p>
    {% if task.isDo %}
    <p>Выполнено</p>
    {% else %}
    <p>Не выполнено</p>
    {% endif %}
    <a href="{% url 'edit_task' task.id %}"
       class="btn {% if not task.isDo %}btn-danger{% else %}btn-success{% endif %}">Редактировать</a>
    <form action="{% url 'delete_task' task.id %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

</div>
{% endif %}
{% endfor %}

{% endif %}


{% else %}
<div class="text-center">
<h4>Чтобы использовать наш сервис, вам нужно авторизироваться или зарегистрироваться.</h4>
</div>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '9-prilozhenij-dlya-planirovaniya-zadach-5.jpg' %}" class="d-block w-100" alt="..." style="width: 700 px; height: 580px; filter: brightness(70%);">
      <div class="carousel-caption d-none d-md-block">
        <h5>Удобство</h5>
        <p>Наш To-Do List предоставляет простой и удобный способ организации задач, помогая вам эффективно управлять вашим временем и задачами. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'shutterstock_1111023.jpg' %}" class="d-block w-100" alt="..." style="width: 700 px; height: 580px; filter: brightness(70%);">
      <div class="carousel-caption d-none d-md-block">
        <h5>Простота</h5>
        <p>Благодаря его интуитивному интерфейсу вы можете легко создавать, отслеживать и завершать задачи, сохраняя свою продуктивность на высоком уровне. </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'shutterstock_625950947.jpg' %}" class="d-block w-100" alt="..." style="width: 700 px; height: 580px; filter: brightness(70%);">
      <div class="carousel-caption d-none d-md-block">
        <h5>Комфорт</h5>
        <p>Кроме того, возможность доступа к списку задач из любого устройства с доступом в интернет делает наш To-Do List идеальным решением для организации вашей повседневной жизни, где бы вы ни находились.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endif %}
{% endblock %}

todolist/main/templates/main/other_users_tasks.html
{% extends 'main/base.html' %}

{% block title %}
Просмотр задач других пользователей
{% endblock %}

{% block content %}
<a href="{% url 'add_task_for_user' %}" class="btn btn-primary">Добавить задачу пользователю</a>
<h2>Задачи других пользователей:</h2>

    {% for task in tasks %}

<div class="alert mt-2 {% if not task.isDo %}alert-danger{% else %}alert-success{% endif %}">
    <h3>{{ task.header }}</h3>
    <h5>Пользователь: {{ task.user.username }}</h5>
    <p>{{ task.dispatcher }}</p>
    {% if task.isDo %}
    <p>Выполнено</p>
    {% else %}
    <p>Не выполнено</p>
    {% endif %}
    <a href="{% url 'edit_task' task.id %}"
       class="btn {% if not task.isDo %}btn-danger{% else %}btn-success{% endif %}">Редактировать</a>
    <form action="{% url 'delete_task' task.id %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

</div>
    {% endfor %}

{% endblock %}